### ISSUE TITLE
Classify media into predefiend categories

### ISSUE THREAD

**Issue by ewertmaster** [we-kode/mml.project#8]
Add the ability to define categories on the media server. 
During the upload of the Media the category for the media shall be selected.
The categories shall be also assigned to the user groups.

On the mobile device the categories she be displayed in accordance with the user rights. 
The User shall be able to switch between the categories.

Example categories: 
- Gottesdienste
- Jugendstunde
- Russische Gottesdienste
- Bibelstunde

**Comment by stummk** [comment]
We provide the concept of groups. These groups can be assigned to clients (when registering and by editing one client) and to media (Only when uploaded, by editing one media record). 
![grafik](https://user-images.githubusercontent.com/12197236/200117603-a5dedcce-9225-4595-b292-f6cab5160ac7.png)

Groups marked as Default will be added automatically to clients and media. You can remove them in the edit dialog.
![grafik](https://user-images.githubusercontent.com/12197236/200117625-5089964a-8aef-46a4-8f72-303cf8f3de63.png)

After a new assignment or change of an assigned group took place it can take up to ~ 1h to take affect.
Clients  see only records of the groups they are assigned to. Defined filters can be used, to get a more granular filtering of media records. These filters are based on the media ID3Tags (Meta-Tags): Interpret, Album and Genre of the record. You can here define your categories on the media you are uploading e.g. the album meta tag.
![grafik](https://user-images.githubusercontent.com/12197236/200117559-16783755-4238-4e63-800c-a10c149aa829.png)

We will not add subcategories to groups, since it will be confusing over the time to manage them.

The only issue I see here is 
- [x] the ability to manage the groups of the records in the upload process.

Are you ok with that?
